Homework 4
ErmakovND/smart-home-2020 pull request #4
Opened 2020-04-01 09:57 UTC by ErmakovND

2020-04-03 11:52 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/app/AppConfiguration.java
> +        SensorEventsManager manager = new SensorEventsManager();
Здесь можно было собрать все бины типа EventHandler из конфигурации https://bit.ly/2UrPgOg

2020-04-03 11:54 UTC, a-ivanov requested changes

2020-04-03 11:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/events/handlers/EventHandlerAdapter.java
> +        typeMap.put("LightIsOn", EventType.LIGHT_ON);
Зачем вы прибиваете гвоздями тут мапу? Думаете, что больше новых типов событий от сторонней библиотеки не будет? Передавайте мапу аргументом и конфигурируйте ее бином.

2020-04-03 11:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/app/AppConfiguration.java
> +        SensorEventsManager manager = new SensorEventsManager();
Соберите все бины типа EventHandler из конфигурации https://bit.ly/2UrPgOg

2020-04-03 11:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/events/handlers/EventHandlerAdapter.java
> +        return new SensorEvent(typeMap.get(event.getEventType()), event.getObjectId());
Проверяйте наличие ключа, иначе NPE.

2020-04-04 14:20 UTC, ErmakovND commented on src/main/java/ru/sbt/mipt/oop/smarthome/events/handlers/EventHandlerAdapter.java
> +        return new SensorEvent(typeMap.get(event.getEventType()), event.getObjectId());
Вроде get вернет null, если не найдет ключа. А все обработчики проверяют тип события, так что null никто обрабатывать не будет.

2020-04-06 14:00 UTC, a-ivanov approved these changes

2020-04-06 14:47 UTC, merged